version: "3.3"
services:

  db: 
    image: mariadb
    container_name: "mdb"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=agsroot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=ags
    ports:
      - "9906:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: "flaskapp"
    ports:
      - "5000:5000"
    volumes:
      - .:/code